// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Modes
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string ModesString = "7c697c09-64b1-4dc2-ba0b-955215206732";
        public static Guid Modes = new Guid(ModesString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ModesMenuGroup = 0x0001;
        public const int ModesSubMenu = 0x0002;
        public const int ModeCommandsGroup = 0x0003;
        public const int ResetCommandsGroup = 0x0004;
        public const int LowPowerCommand = 0x0100;
        public const int FocusCommand = 0x0101;
        public const int PerformanceCommand = 0x0102;
        public const int PresenterCommand = 0x0103;
        public const int ResetSettingsCommand = 0x0104;
        public const int SettingsCommand = 0x0105;
    }
}
